CREATE TABLE AUTH_TOKEN
(
    ID         NUMBER(19,0)       NOT NULL,
    VERSION    NUMBER(19,0)       NOT NULL,
    AUTH_ROLES LONG               NOT NULL,
    TOKEN      VARCHAR2(255 CHAR) NOT NULL,
    USER_ID    NUMBER(19,0)       NOT NULL
)
/
ALTER TABLE AUTH_TOKEN
    ADD CONSTRAINT SYS_C0011702
    PRIMARY KEY (ID)   
/
ALTER TABLE AUTH_TOKEN
    ADD CONSTRAINT UK_PL6HLEYEX3OFOAKLDUHBYRETW
    UNIQUE (TOKEN)   
/
CREATE TABLE BASE_REPORT
(
    ID              NUMBER(19,0)        NOT NULL,
    VERSION         NUMBER(19,0)        NOT NULL,
    ACTION_TYPE     VARCHAR2(256 CHAR)  NOT NULL,
    AUTHOR          VARCHAR2(255 CHAR)  NOT NULL,
    CTX_NAME        VARCHAR2(255 CHAR)      NULL,
    CTX_PROJECT     VARCHAR2(255 CHAR)  NOT NULL,
    CTX_TYPE        VARCHAR2(255 CHAR)      NULL,
    DATE_COMPLETED  TIMESTAMP(6)        NOT NULL,
    DATE_STARTED    TIMESTAMP(6)        NOT NULL,
    MAPREF_URI      VARCHAR2(255 CHAR)      NULL,
    MESSAGE         CLOB                NOT NULL,
    NODE            VARCHAR2(255 CHAR)      NULL,
    REPORT_ID       VARCHAR2(3072 CHAR)     NULL,
    STATUS          VARCHAR2(256 CHAR)  NOT NULL,
    TAGS            VARCHAR2(255 CHAR)      NULL,
    TITLE           CLOB                NOT NULL,
    CLASS           VARCHAR2(255 CHAR)  NOT NULL,
    ABORTED_BY_USER VARCHAR2(255 CHAR)      NULL,
    ADHOC_EXECUTION NUMBER(1,0)             NULL,
    ADHOC_SCRIPT    CLOB                    NULL,
    CTX_COMMAND     VARCHAR2(255 CHAR)      NULL,
    CTX_CONTROLLER  VARCHAR2(255 CHAR)      NULL,
    JC_EXEC_ID      VARCHAR2(255 CHAR)      NULL,
    JC_JOB_ID       VARCHAR2(255 CHAR)      NULL
)
/
ALTER TABLE BASE_REPORT
    ADD CONSTRAINT SYS_C0011778
    PRIMARY KEY (ID)
/
CREATE TABLE EXECUTION
(
    ID                        NUMBER(19,0)       NOT NULL,
    VERSION                   NUMBER(19,0)       NOT NULL,
    ABORTEDBY                 VARCHAR2(255 CHAR)     NULL,
    ARG_STRING                CLOB                   NULL,
    CANCELLED                 NUMBER(1,0)        NOT NULL,
    DATE_COMPLETED            TIMESTAMP(6)           NULL,
    DATE_STARTED              TIMESTAMP(6)           NULL,
    DO_NODEDISPATCH           NUMBER(1,0)            NULL,
    FAILED_NODE_LIST          CLOB                   NULL,
    FILTER                    CLOB                   NULL,
    LOGLEVEL                  VARCHAR2(255 CHAR)     NULL,
    NODE_EXCLUDE              CLOB                   NULL,
    NODE_EXCLUDE_NAME         CLOB                   NULL,
    NODE_EXCLUDE_OS_ARCH      CLOB                   NULL,
    NODE_EXCLUDE_OS_FAMILY    CLOB                   NULL,
    NODE_EXCLUDE_OS_NAME      CLOB                   NULL,
    NODE_EXCLUDE_OS_VERSION   CLOB                   NULL,
    NODE_EXCLUDE_PRECEDENCE   NUMBER(1,0)            NULL,
    NODE_EXCLUDE_TAGS         CLOB                   NULL,
    NODE_INCLUDE              CLOB                   NULL,
    NODE_INCLUDE_NAME         CLOB                   NULL,
    NODE_INCLUDE_OS_ARCH      CLOB                   NULL,
    NODE_INCLUDE_OS_FAMILY    CLOB                   NULL,
    NODE_INCLUDE_OS_NAME      CLOB                   NULL,
    NODE_INCLUDE_OS_VERSION   CLOB                   NULL,
    NODE_INCLUDE_TAGS         CLOB                   NULL,
    NODE_KEEPGOING            NUMBER(1,0)            NULL,
    NODE_RANK_ATTRIBUTE       VARCHAR2(255 CHAR)     NULL,
    NODE_RANK_ORDER_ASCENDING NUMBER(1,0)            NULL,
    NODE_THREADCOUNT          NUMBER(10,0)           NULL,
    OUTPUTFILEPATH            CLOB                   NULL,
    PROJECT                   VARCHAR2(255 CHAR) NOT NULL,
    RETRY                     CLOB                   NULL,
    RETRY_ATTEMPT             NUMBER(10,0)           NULL,
    RETRY_EXECUTION_ID        NUMBER(19,0)           NULL,
    SCHEDULED_EXECUTION_ID    NUMBER(19,0)           NULL,
    SERVER_NODEUUID           VARCHAR2(36 CHAR)      NULL,
    STATUS                    VARCHAR2(255 CHAR)     NULL,
    SUCCEEDED_NODE_LIST       CLOB                   NULL,
    TIMED_OUT                 NUMBER(1,0)            NULL,
    TIMEOUT                   CLOB                   NULL,
    RDUSER                    VARCHAR2(255 CHAR) NOT NULL,
    WILL_RETRY                NUMBER(1,0)            NULL,
    WORKFLOW_ID               NUMBER(19,0)           NULL,
    ORCHESTRATOR_ID           NUMBER(19,0)           NULL
)
/
ALTER TABLE EXECUTION
    ADD CONSTRAINT SYS_C0011784
    PRIMARY KEY (ID)   
/

CREATE TABLE LOG_FILE_STORAGE_REQUEST
(
    ID           NUMBER(19,0)       NOT NULL,
    VERSION      NUMBER(19,0)       NOT NULL,
    COMPLETED    NUMBER(1,0)        NOT NULL,
    DATE_CREATED TIMESTAMP(6)       NOT NULL,
    EXECUTION_ID NUMBER(19,0)       NOT NULL,
    FILETYPE     VARCHAR2(255 CHAR)     NULL,
    LAST_UPDATED TIMESTAMP(6)       NOT NULL,
    PLUGIN_NAME  VARCHAR2(255 CHAR) NOT NULL
)
/
ALTER TABLE LOG_FILE_STORAGE_REQUEST
    ADD CONSTRAINT SYS_C0011710
    PRIMARY KEY (ID)
   
/

CREATE TABLE NODE_FILTER
(
    ID                      NUMBER(19,0)       NOT NULL,
    VERSION                 NUMBER(19,0)       NOT NULL,
    FILTER                  CLOB                   NULL,
    NAME                    VARCHAR2(255 CHAR) NOT NULL,
    NODE_EXCLUDE            CLOB                   NULL,
    NODE_EXCLUDE_NAME       CLOB                   NULL,
    NODE_EXCLUDE_OS_ARCH    CLOB                   NULL,
    NODE_EXCLUDE_OS_FAMILY  CLOB                   NULL,
    NODE_EXCLUDE_OS_NAME    CLOB                   NULL,
    NODE_EXCLUDE_OS_VERSION CLOB                   NULL,
    NODE_EXCLUDE_PRECEDENCE NUMBER(1,0)            NULL,
    NODE_EXCLUDE_TAGS       CLOB                   NULL,
    NODE_INCLUDE            CLOB                   NULL,
    NODE_INCLUDE_NAME       CLOB                   NULL,
    NODE_INCLUDE_OS_ARCH    CLOB                   NULL,
    NODE_INCLUDE_OS_FAMILY  CLOB                   NULL,
    NODE_INCLUDE_OS_NAME    CLOB                   NULL,
    NODE_INCLUDE_OS_VERSION CLOB                   NULL,
    NODE_INCLUDE_TAGS       CLOB                   NULL,
    PROJECT                 VARCHAR2(255 CHAR)     NULL,
    USER_ID                 NUMBER(19,0)       NOT NULL
)
/
ALTER TABLE NODE_FILTER
    ADD CONSTRAINT SYS_C0011789
    PRIMARY KEY (ID)    
/

CREATE TABLE NOTIFICATION
(
    ID                     NUMBER(19,0)       NOT NULL,
    VERSION                NUMBER(19,0)       NOT NULL,
    CONTENT                LONG                   NULL,
    EVENT_TRIGGER          VARCHAR2(255 CHAR) NOT NULL,
    SCHEDULED_EXECUTION_ID NUMBER(19,0)       NOT NULL,
    TYPE                   VARCHAR2(255 CHAR) NOT NULL
)
/
ALTER TABLE NOTIFICATION
    ADD CONSTRAINT SYS_C0011716
    PRIMARY KEY (ID)
    
/

CREATE TABLE ORCHESTRATOR
(
    ID      NUMBER(19,0)       NOT NULL,
    VERSION NUMBER(19,0)       NOT NULL,
    CONTENT LONG                   NULL,
    TYPE    VARCHAR2(255 CHAR) NOT NULL
)
/
ALTER TABLE ORCHESTRATOR
    ADD CONSTRAINT SYS_C0011933
    PRIMARY KEY (ID)   
/

CREATE TABLE PLUGIN_META
(
    ID           NUMBER(19,0)       NOT NULL,
    VERSION      NUMBER(19,0)       NOT NULL,
    DATE_CREATED TIMESTAMP(6)       NOT NULL,
    JSON_DATA    LONG                   NULL,
    DATA_KEY     VARCHAR2(255 CHAR) NOT NULL,
    LAST_UPDATED TIMESTAMP(6)       NOT NULL,
    PROJECT      VARCHAR2(255 CHAR) NOT NULL
)
/
ALTER TABLE PLUGIN_META
    ADD CONSTRAINT SYS_C0011727
    PRIMARY KEY (ID)   
/
CREATE TABLE PROJECT
(
    ID           NUMBER(19,0)       NOT NULL,
    VERSION      NUMBER(19,0)       NOT NULL,
    DATE_CREATED TIMESTAMP(6)       NOT NULL,
    DESCRIPTION  VARCHAR2(255 CHAR)     NULL,
    LAST_UPDATED TIMESTAMP(6)       NOT NULL,
    NAME         VARCHAR2(255 CHAR) NOT NULL
)
/
CREATE TABLE RDOPTION
(
    ID                     NUMBER(19,0)        NOT NULL,
    VERSION                NUMBER(19,0)        NOT NULL,
    DEFAULT_VALUE          CLOB                    NULL,
    DELIMITER              VARCHAR2(255 CHAR)      NULL,
    DESCRIPTION            CLOB                    NULL,
    ENFORCED               NUMBER(1,0)         NOT NULL,
    MULTIVALUED            NUMBER(1,0)             NULL,
    NAME                   VARCHAR2(255 CHAR)  NOT NULL,
    REGEX                  CLOB                    NULL,
    REQUIRED               NUMBER(1,0)             NULL,
    SCHEDULED_EXECUTION_ID NUMBER(19,0)            NULL,
    SECURE_EXPOSED         NUMBER(1,0)             NULL,
    SECURE_INPUT           NUMBER(1,0)             NULL,
    SORT_INDEX             NUMBER(10,0)            NULL,
    VALUES_URL             VARCHAR2(255 CHAR)      NULL,
    VALUES_URL_BLOB        VARCHAR2(3000 CHAR)     NULL,
    DEFAULT_STORAGE_PATH   VARCHAR2(255 CHAR)      NULL,
    VALUES_URL_LONG        VARCHAR2(3000 CHAR)     NULL
)
/
ALTER TABLE RDOPTION
    ADD CONSTRAINT SYS_C0011794
    PRIMARY KEY (ID)
/


CREATE TABLE RDOPTION_VALUES
(
    OPTION_ID     NUMBER(19,0)     NULL,
    VALUES_STRING LONG             NULL
)
/

CREATE TABLE RDUSER
(
    ID             NUMBER(19,0)       NOT NULL,
    VERSION        NUMBER(19,0)       NOT NULL,
    DASHBOARD_PREF VARCHAR2(255 CHAR)     NULL,
    DATE_CREATED   TIMESTAMP(6)       NOT NULL,
    EMAIL          VARCHAR2(255 CHAR)     NULL,
    FILTER_PREF    VARCHAR2(255 CHAR)     NULL,
    FIRST_NAME     VARCHAR2(255 CHAR)     NULL,
    LAST_NAME      VARCHAR2(255 CHAR)     NULL,
    LAST_UPDATED   TIMESTAMP(6)       NOT NULL,
    LOGIN          VARCHAR2(255 CHAR) NOT NULL,
    PASSWORD       VARCHAR2(255 CHAR)     NULL
)
/
ALTER TABLE RDUSER
    ADD CONSTRAINT SYS_C0011739
    PRIMARY KEY (ID)
/

CREATE TABLE REPORT_FILTER
(
    ID                   NUMBER(19,0)       NOT NULL,
    VERSION              NUMBER(19,0)       NOT NULL,
    CMD_FILTER           VARCHAR2(255 CHAR)     NULL,
    DOENDAFTER_FILTER    NUMBER(1,0)        NOT NULL,
    DOENDBEFORE_FILTER   NUMBER(1,0)        NOT NULL,
    DOSTARTAFTER_FILTER  NUMBER(1,0)        NOT NULL,
    DOSTARTBEFORE_FILTER NUMBER(1,0)        NOT NULL,
    ENDAFTER_FILTER      TIMESTAMP(6)           NULL,
    ENDBEFORE_FILTER     TIMESTAMP(6)           NULL,
    JOB_FILTER           VARCHAR2(255 CHAR)     NULL,
    JOB_ID_FILTER        VARCHAR2(255 CHAR)     NULL,
    MAPREF_URI_FILTER    VARCHAR2(255 CHAR)     NULL,
    MESSAGE_FILTER       VARCHAR2(255 CHAR)     NULL,
    NAME                 VARCHAR2(255 CHAR) NOT NULL,
    NODE_FILTER          VARCHAR2(255 CHAR)     NULL,
    OBJ_FILTER           VARCHAR2(255 CHAR)     NULL,
    PROJ_FILTER          VARCHAR2(255 CHAR) NOT NULL,
    RECENT_FILTER        VARCHAR2(255 CHAR)     NULL,
    REPORT_ID_FILTER     VARCHAR2(255 CHAR)     NULL,
    STARTAFTER_FILTER    TIMESTAMP(6)           NULL,
    STARTBEFORE_FILTER   TIMESTAMP(6)           NULL,
    STAT_FILTER          VARCHAR2(255 CHAR)     NULL,
    TAGS_FILTER          VARCHAR2(255 CHAR)     NULL,
    TITLE_FILTER         VARCHAR2(255 CHAR)     NULL,
    TYPE_FILTER          VARCHAR2(255 CHAR)     NULL,
    USER_ID              NUMBER(19,0)       NOT NULL,
    USER_FILTER          VARCHAR2(255 CHAR)     NULL
)
/
ALTER TABLE REPORT_FILTER
    ADD CONSTRAINT SYS_C0011749
    PRIMARY KEY (ID)
   
/
ALTER TABLE REPORT_FILTER
    ADD CONSTRAINT UK_9DH5OWJLBB2X223GOPAQ6T0JM
    UNIQUE (NAME)   
/

CREATE TABLE SCHEDULED_EXECUTION
(
    ID                          NUMBER(19,0)        NOT NULL,
    VERSION                     NUMBER(19,0)        NOT NULL,
    ARG_STRING                  CLOB                    NULL,
    DATE_CREATED                TIMESTAMP(6)        NOT NULL,
    DAY_OF_MONTH                VARCHAR2(255 CHAR)      NULL,
    DAY_OF_WEEK                 VARCHAR2(255 CHAR)      NULL,
    DESCRIPTION                 CLOB                    NULL,
    DO_NODEDISPATCH             NUMBER(1,0)             NULL,
    EXEC_COUNT                  NUMBER(19,0)            NULL,
    FILTER                      CLOB                    NULL,
    GROUP_PATH                  VARCHAR2(2048 CHAR)     NULL,
    HOUR                        VARCHAR2(255 CHAR)      NULL,
    JOB_NAME                    VARCHAR2(1024 CHAR) NOT NULL,
    LAST_UPDATED                TIMESTAMP(6)        NOT NULL,
    LOGLEVEL                    VARCHAR2(255 CHAR)      NULL,
    MINUTE                      VARCHAR2(255 CHAR)      NULL,
    MONTH                       VARCHAR2(255 CHAR)      NULL,
    MULTIPLE_EXECUTIONS         NUMBER(1,0)             NULL,
    NEXT_EXECUTION              TIMESTAMP(6)            NULL,
    NODE_EXCLUDE                CLOB                    NULL,
    NODE_EXCLUDE_NAME           CLOB                    NULL,
    NODE_EXCLUDE_OS_ARCH        CLOB                    NULL,
    NODE_EXCLUDE_OS_FAMILY      CLOB                    NULL,
    NODE_EXCLUDE_OS_NAME        CLOB                    NULL,
    NODE_EXCLUDE_OS_VERSION     CLOB                    NULL,
    NODE_EXCLUDE_PRECEDENCE     NUMBER(1,0)             NULL,
    NODE_EXCLUDE_TAGS           CLOB                    NULL,
    NODE_INCLUDE                CLOB                    NULL,
    NODE_INCLUDE_NAME           CLOB                    NULL,
    NODE_INCLUDE_OS_ARCH        CLOB                    NULL,
    NODE_INCLUDE_OS_FAMILY      CLOB                    NULL,
    NODE_INCLUDE_OS_NAME        CLOB                    NULL,
    NODE_INCLUDE_OS_VERSION     CLOB                    NULL,
    NODE_INCLUDE_TAGS           CLOB                    NULL,
    NODE_KEEPGOING              NUMBER(1,0)             NULL,
    NODE_RANK_ATTRIBUTE         VARCHAR2(255 CHAR)      NULL,
    NODE_RANK_ORDER_ASCENDING   NUMBER(1,0)             NULL,
    NODE_THREADCOUNT            NUMBER(10,0)            NULL,
    PROJECT                     VARCHAR2(255 CHAR)  NOT NULL,
    RETRY                       CLOB                    NULL,
    SCHEDULED                   NUMBER(1,0)         NOT NULL,
    SECONDS                     VARCHAR2(255 CHAR)      NULL,
    SERVER_NODEUUID             VARCHAR2(36 CHAR)       NULL,
    TIMEOUT                     CLOB                    NULL,
    TOTAL_TIME                  NUMBER(19,0)            NULL,
    RDUSER                      VARCHAR2(255 CHAR)      NULL,
    USER_ROLE_LIST              CLOB                    NULL,
    UUID                        VARCHAR2(255 CHAR)      NULL,
    WORKFLOW_ID                 NUMBER(19,0)            NULL,
    YEAR                        VARCHAR2(255 CHAR)      NULL,
    EXECUTION_ENABLED           NUMBER(1,0)             NULL,
    LOG_OUTPUT_THRESHOLD        VARCHAR2(256 CHAR)      NULL,
    LOG_OUTPUT_THRESHOLD_ACTION VARCHAR2(256 CHAR)      NULL,
    LOG_OUTPUT_THRESHOLD_STATUS VARCHAR2(256 CHAR)      NULL,
    NODES_SELECTED_BY_DEFAULT   NUMBER(1,0)             NULL,
    ORCHESTRATOR_ID             NUMBER(19,0)            NULL,
    SCHEDULE_ENABLED            NUMBER(1,0)             NULL
)
/
ALTER TABLE SCHEDULED_EXECUTION
    ADD CONSTRAINT SYS_C0011802
    PRIMARY KEY (ID)   
/

CREATE TABLE SCHEDULED_EXECUTION_FILTER
(
    ID              NUMBER(19,0)       NOT NULL,
    VERSION         NUMBER(19,0)       NOT NULL,
    DESC_FILTER     VARCHAR2(255 CHAR)     NULL,
    GROUP_PATH      VARCHAR2(255 CHAR)     NULL,
    IDLIST          VARCHAR2(255 CHAR)     NULL,
    JOB_FILTER      VARCHAR2(255 CHAR)     NULL,
    LOGLEVEL_FILTER VARCHAR2(255 CHAR)     NULL,
    NAME            VARCHAR2(255 CHAR) NOT NULL,
    PROJ_FILTER     VARCHAR2(255 CHAR)     NULL,
    USER_ID         NUMBER(19,0)       NOT NULL
)
/
ALTER TABLE SCHEDULED_EXECUTION_FILTER
    ADD CONSTRAINT SYS_C0011754
    PRIMARY KEY (ID)
/

CREATE TABLE STORAGE
(
    ID           NUMBER(19,0)        NOT NULL,
    VERSION      NUMBER(19,0)        NOT NULL,
    DATA         BLOB                    NULL,
    DATE_CREATED TIMESTAMP(6)        NOT NULL,
    DIR          VARCHAR2(2048 CHAR)     NULL,
    JSON_DATA    CLOB                    NULL,
    LAST_UPDATED TIMESTAMP(6)        NOT NULL,
    NAME         VARCHAR2(1024 CHAR) NOT NULL,
    NAMESPACE    VARCHAR2(255 CHAR)      NULL,
    PATH_SHA     VARCHAR2(40 CHAR)   NOT NULL
)
/
ALTER TABLE STORAGE
    ADD CONSTRAINT SYS_C0011810
    PRIMARY KEY (ID)   
/
ALTER TABLE STORAGE
    ADD CONSTRAINT SYS_C0011811
    UNIQUE (PATH_SHA)    
/
CREATE TABLE WORKFLOW
(
    ID          NUMBER(19,0)      NOT NULL,
    VERSION     NUMBER(19,0)      NOT NULL,
    KEEPGOING   NUMBER(1,0)       NOT NULL,
    STRATEGY    VARCHAR2(10 CHAR) NOT NULL,
    THREADCOUNT NUMBER(10,0)      NOT NULL
)
/
ALTER TABLE WORKFLOW
    ADD CONSTRAINT SYS_C0011760
    PRIMARY KEY (ID)
/

CREATE TABLE WORKFLOW_STEP
(
    ID                        NUMBER(19,0)        NOT NULL,
    VERSION                   NUMBER(19,0)        NOT NULL,
    DESCRIPTION               VARCHAR2(1024 CHAR)     NULL,
    ERROR_HANDLER_ID          NUMBER(19,0)            NULL,
    KEEPGOING_ON_SUCCESS      NUMBER(1,0)             NULL,
    CLASS                     VARCHAR2(255 CHAR)  NOT NULL,
    JSON_DATA                 CLOB                    NULL,
    NODE_STEP                 NUMBER(1,0)             NULL,
    TYPE                      VARCHAR2(255 CHAR)      NULL,
    ADHOC_EXECUTION           NUMBER(1,0)             NULL,
    ADHOC_FILEPATH            CLOB                    NULL,
    ADHOC_LOCAL_STRING        CLOB                    NULL,
    ADHOC_REMOTE_STRING       CLOB                    NULL,
    ARG_STRING                CLOB                    NULL,
    FILE_EXTENSION            CLOB                    NULL,
    INTERPRETER_ARGS_QUOTED   NUMBER(1,0)             NULL,
    SCRIPT_INTERPRETER        CLOB                    NULL,
    JOB_GROUP                 VARCHAR2(2048 CHAR)     NULL,
    JOB_NAME                  VARCHAR2(1024 CHAR)     NULL,
    NODE_FILTER               CLOB                    NULL,
    NODE_KEEPGOING            NUMBER(1,0)             NULL,
    NODE_RANK_ATTRIBUTE       CLOB                    NULL,
    NODE_RANK_ORDER_ASCENDING NUMBER(1,0)             NULL,
    NODE_THREADCOUNT          NUMBER(10,0)            NULL
)
/
ALTER TABLE WORKFLOW_STEP
    ADD CONSTRAINT SYS_C0011815
    PRIMARY KEY (ID)    
/

CREATE TABLE WORKFLOW_WORKFLOW_STEP
(
    WORKFLOW_COMMANDS_ID NUMBER(19,0)     NULL,
    WORKFLOW_STEP_ID     NUMBER(19,0)     NULL,
    COMMANDS_IDX         NUMBER(10,0)     NULL
)
/



ALTER TABLE AUTH_TOKEN
    ADD CONSTRAINT FK_AIQC20KPJASTH5BXOGSRAGOIF
    FOREIGN KEY (USER_ID)
    REFERENCES RDUSER (ID)
    ENABLE
/

ALTER TABLE LOG_FILE_STORAGE_REQUEST
    ADD CONSTRAINT FK_TRQSA9SO0QCV6OKCD6FAN88YF
    FOREIGN KEY (EXECUTION_ID)
    REFERENCES EXECUTION (ID)
    ENABLE
/
ALTER TABLE EXECUTION
    ADD CONSTRAINT FK_LTIUKR4BDTI8HCLO49O2G6V9O
    FOREIGN KEY (ORCHESTRATOR_ID)
    REFERENCES ORCHESTRATOR (ID)
    ENABLE
/
ALTER TABLE EXECUTION
    ADD CONSTRAINT FK_FOFKK7VJ9H2BDCQQICS5USTR6
    FOREIGN KEY (WORKFLOW_ID)
    REFERENCES WORKFLOW (ID)
    ENABLE
/
ALTER TABLE EXECUTION
    ADD CONSTRAINT FK_A908HRCN9U20EAYG6AKKEPBL1
    FOREIGN KEY (RETRY_EXECUTION_ID)
    REFERENCES EXECUTION (ID)
    ENABLE
/
ALTER TABLE EXECUTION
    ADD CONSTRAINT FK_6SHMC1Y7SH51X03AOVFUALOKA
    FOREIGN KEY (SCHEDULED_EXECUTION_ID)
    REFERENCES SCHEDULED_EXECUTION (ID)
    ENABLE
/

ALTER TABLE NODE_FILTER
    ADD CONSTRAINT FK_B7Y0UH7DSIIKF3GXN8RXVP1AJ
    FOREIGN KEY (USER_ID)
    REFERENCES RDUSER (ID)
    ENABLE
/

ALTER TABLE NOTIFICATION
    ADD CONSTRAINT FK_JNK8QDBQ6E3WWKCNI79WCREWY
    FOREIGN KEY (SCHEDULED_EXECUTION_ID)
    REFERENCES SCHEDULED_EXECUTION (ID)
    ENABLE
/


ALTER TABLE SCHEDULED_EXECUTION
    ADD CONSTRAINT FK_MNS7YXW0CX9MSUK59X9F2B4LV
    FOREIGN KEY (ORCHESTRATOR_ID)
    REFERENCES ORCHESTRATOR (ID)
    ENABLE
/

ALTER TABLE RDOPTION_VALUES
    ADD CONSTRAINT FK_P6S9N018KM1EMN0A0Q04YGC72
    FOREIGN KEY (OPTION_ID)
    REFERENCES RDOPTION (ID)
    ENABLE
/
ALTER TABLE RDOPTION
    ADD CONSTRAINT FK_JRAXRDPUL0NE9EEDIY1XJLSFV
    FOREIGN KEY (SCHEDULED_EXECUTION_ID)
    REFERENCES SCHEDULED_EXECUTION (ID)
    ENABLE
/



ALTER TABLE REPORT_FILTER
    ADD CONSTRAINT FK_BFOS9O64CND2I2XFNX7IL0TIX
    FOREIGN KEY (USER_ID)
    REFERENCES RDUSER (ID)
    ENABLE
/
ALTER TABLE SCHEDULED_EXECUTION_FILTER
    ADD CONSTRAINT FK_6R7OK07N10VBSBL6F1CK2H58U
    FOREIGN KEY (USER_ID)
    REFERENCES RDUSER (ID)
    ENABLE
/


ALTER TABLE SCHEDULED_EXECUTION
    ADD CONSTRAINT SYS_C0011803
    UNIQUE (UUID)
/
ALTER TABLE SCHEDULED_EXECUTION
    ADD CONSTRAINT FK_JLN7B7A683UWKL4FG6KPACQNP
    FOREIGN KEY (WORKFLOW_ID)
    REFERENCES WORKFLOW (ID)
    ENABLE
/

ALTER TABLE WORKFLOW_STEP
    ADD CONSTRAINT FK_8BBF05V4F6VO5O3CGP69AWCUE
    FOREIGN KEY (ERROR_HANDLER_ID)
    REFERENCES WORKFLOW_STEP (ID)
    ENABLE
/

ALTER TABLE WORKFLOW_WORKFLOW_STEP
    ADD CONSTRAINT FK_9PKEY6K5FDO6WORGQUAKKH7D1
    FOREIGN KEY (WORKFLOW_STEP_ID)
    REFERENCES WORKFLOW_STEP (ID)
    ENABLE
/
